### ISSUE TITLE
Installing octopress-paginate gem breaks octopress3

### ISSUE THREAD

**Issue by ashak** [octopress/paginate#16]
I've been playing with octopress3, created some posts, all was well.

I installed the octopress-paginate gem as described in the Readme.md, I added this gem to my site's Gemfile in the :jekyll_plugins group, used bundle to install the gems and added the gem to my Jekyll _config.yaml.

Now if I try to create a page or a post I get this:

/home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:320:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:136:in`<top (required)>'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-paginate-1.1.2/lib/octopress-paginate.rb:1:in `require'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-paginate-1.1.2/lib/octopress-paginate.rb:1:in`<top (required)>'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:30:in `require'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:30:in`block in require_gems'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:27:in `each'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:27:in`require_gems'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in`setup'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-3.0.11/lib/octopress.rb:68:in`new'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-3.0.11/lib/octopress.rb:68:in `read_site'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-3.0.11/lib/octopress.rb:61:in`site'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-3.0.11/lib/octopress/commands/new.rb:33:in `block (3 levels) in init_with_program'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in`call'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in`each'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in`go'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/gems/octopress-3.0.11/bin/octopress:8:in`<top (required)>'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/bin/octopress:23:in `load'
    from /home/garyr/.rbenv/versions/2.1.4/gemsets/octopress3/bin/octopress:23:in`<main>'

**Comment by sammcj** [comment]
Doesn't look to work with jekyll 3 either:

```
~/git/smcleod (master|✚2…) % jekyll b
Configuration file: /Users/samm/git/smcleod/_config.yml
/Users/samm/.rvm/gems/ruby-2.2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:320:in `<module:Jekyll>': cannot load such file -- jekyll/post (LoadError)
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/octopress-hooks-2.6.1/lib/octopress-hooks.rb:136:in `<top (required)>'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/octopress-paginate-1.1.2/lib/octopress-paginate.rb:1:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/octopress-paginate-1.1.2/lib/octopress-paginate.rb:1:in `<top (required)>'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    from /Users/samm/git/smcleod/_plugins/bundler.rb:3:in `<top (required)>'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `each'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `each'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:97:in `setup'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/site.rb:49:in `initialize'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `new'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
    from /Users/samm/.rvm/gems/ruby-2.2.1/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
    from /Users/samm/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `load'
    from /Users/samm/.rvm/gems/ruby-2.2.1/bin/jekyll:23:in `<main>'
    from /Users/samm/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/samm/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mshick** [comment]
Same here, also on jekyll 3. same trace as @sammcj above

**Comment by mshick** [comment]
I'm guessing this has to do with the removal of the unique "posts" collection, and now treating posts as just another collection. The class this line is attempting to extend no longer exists in the Jekyll codebase. I'm not seeing any easy fixes, and wonder if this module will need a rewrite to support jekyll3.

FYI, this commit removed that class: https://github.com/jekyll/jekyll/commit/b89f943bf22bd7f36c8378791ca543e16a59f442

I should look at open PRs before talking. Seems like this problem is known and being handled. https://github.com/octopress/paginate/pull/7
