### ISSUE TITLE
Paginate category

### ISSUE THREAD

**Issue by alessiofx** [octopress/paginate#37]
When I use:

paginate:
  collection: work
  per_page: 10
  limit: false 
  permalink: /:num/
  categories: [Advertising]

compile error:
`Incremental build: disabled. Enable with --incremental
      Generating...
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.
       Deprecation: Document#categories is now a key in the #data hash.
       Deprecation: Called by /Library/Ruby/Gems/2.0.0/gems/octopress-paginate-1.2.0/lib/octopress-paginate.rb:148:in `block in collection'.`

Why ??

**Comment by Saifadin** [comment]
I have the same problem, will the devs respond to this?

**Comment by alisaono** [comment]
Same issue here.

**Comment by aprilmintacpineda** [comment]
This is a duplicate of #35
